INSERT INTO TIPOAVALIACAO(NOME) VALUES ('Tipo 01');


INSERT INTO TIPOPERGUNTA(NOME) VALUES ('Aberta(Discursivo)');
INSERT INTO TIPOPERGUNTA(NOME) VALUES ('Escolha única');
INSERT INTO TIPOPERGUNTA(NOME) VALUES ('Multipla escolha');